version: '3'

services: 

  mongodb:
    image: mongo:4.2.1
    ports:
      - 27017-27019:27017-27019
    container_name: mongodb
    volumes: 
      - ./db:/data/db

  server: 
    build:
      context: ./server
      args:
        NODE_ENV: ${NODE_ENV}
    depends_on:
      - mongodb
    volumes:
      - ./server:${PATH_CONTAINER}
      - ${PATH_CONTAINER}/node_modules
      - vol:${PATH_CONTAINER}/logs
    ports:
      - 8080:8080
      - 9229:9229
    working_dir: ${PATH_CONTAINER}
    env_file:
      - ./.env

  # logs: 
  #   build: ./logs
  #   restart: always
  #   ports:
  #     - 5000:5000
  #   volumes:
  #     - vol:${PATH_CONTAINER}/logs
  #   working_dir: ${PATH_CONTAINER}
  #   depends_on:
  #     - server

volumes: 
  vol:
